### PR TITLE
Arch Linux: Install ruby-toml as native package

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by alexjfisher** [comment]
What happens if you've already been using the module, and the gem has been installed?  Ideally we should remove it?

**Comment by alexjfisher** [comment]
`pacman` is already the default package provider for arch, so does this actually do anything?

**Comment by alexjfisher** [comment]
The default for this parameter is `undef` https://github.com/voxpupuli/puppet-grafana/blob/master/data/common.yaml#L33 and this isn't overridden anywhere else. (The default should probably just be in the init.pp IMO, but that's a separate conversation!)

**Review by alexjfisher — CHANGES_REQUESTED** [review]
I'm unconvinced this PR does anything, but let me know if I've missed something!

**Comment by bastelfreak** [comment]
yes you're right, we can close the PR!

**Pull request closed without merging**
