### PR TITLE
BREAKING: Create grafana_plugin resource type and change grafana::plugins

### PR DESCRIPTION
**Pull request by wyardley**
This switches grafana plugins to be configured via type / provider.
- It replaces the `grafana::plugin` defined type with a (not backwards-compatible) `grafana::plugins` passthrough to create_resources.
- It now implements deinstallation [ensuring specific versions is not yet implemented], and the ability to run `puppet resource ...`
- Installing a plugin will restart the service (currently not configurable).

### CODE REVIEW

**Comment by wyardley** [comment]
@bastelfreak @ekohl did a few more updates. Could still probably have some slight improvements, but I think this is ready for review.

**Comment by carazzim0** [comment]
Is there a way to use this with http_proxy since my Grafana servers are not allowed to connect to the internet directly?

**Comment by carazzim0** [comment]
@wyardley currently I use my custom provider for plugins using an exec ressource. This is the only way I can install plugins.
```
  exec{"install ${plugin}":
    environment => [
      "http_proxy=http://${proxy}",
      "https_proxy=http://${proxy}",
    ],
    command     => "/usr/sbin/grafana-cli plugins install ${plugin}",
    creates     => "/var/lib/grafana/plugins/${plugin}",
    notify      => Service['grafana-server'],
  }
```
How could this be implemented?

**Comment by wyardley** [comment]
@carazzim0 I'm not sure whether adding support for it would be useful for the module in general 
From a quick search, seems like it might work to add a `Exec { environment => [ "foo=$bar" ] }` in the Puppet run before including the class? Or, you can set env variables for the provider's call in 
https://github.com/voxpupuli/puppet-grafana/blob/master/lib/puppet/provider/grafana_plugin/grafana_cli.rb#L3

similar to what's done here: 
https://github.com/voxpupuli/puppet-rabbitmq/blob/master/lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb#L11

**Pull request merged**
