### PR TITLE
Fix #152 : multi arch send out a notice

### LINKED ISSUE #152: multi arch send out a notice
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.4
- Ruby:  2.5.3p105
- Distribution: Ubuntu/Debian
- Module version: master branch

If you have enable i386 arch enabled you get a notice when running apt-get update:

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.grafana.com/oss/deb stable InRelease' doesn't support architecture 'i386'

By default apt::source will try to get all the enabled architectures unless you specify the available architectures on the repo.

As far as i can tell, only amd64 and arm architectures are available on the repo.

Should i make a PR to list the available arch on the repo ?

### PR DESCRIPTION
**Pull request by elfranne**
Fixes #152 
Available architectures : https://grafana.com/grafana/download?platform=linux

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @elfranne, can you take a look at the failed unit tests?

**Comment by bastelfreak** [comment]
The beaker tests will fail because of https://github.com/puppetlabs/beaker-puppet/pull/102. We need to rerun them after it got merged and released.

**Comment by elfranne** [comment]
New version of beaker has been released.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
