### PR TITLE
modulesync 5.3.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
@bastelfreak this appears to fail on Archlinux because `/var/lib/grafana` isn't recreated on package install. Is that expected or is it a packaging bug?

**Comment by bastelfreak** [comment]
@ekohl I think that's expected. if you check https://archlinux.org/packages/community/x86_64/grafana/ , at the bottom is [View the file list for grafana](https://archlinux.org/packages/community/x86_64/grafana/files/). The package puts nothing into `/var/lib`

**Comment by ekohl** [comment]
Still, the question remains: do we need to solve it in our module (either in the test suite or in the manifest) or should the Arch package ensure `/var/lib/grafana`?

**Comment by bastelfreak** [comment]
I pulled the arch linux related changes into https://github.com/voxpupuli/puppet-grafana/pull/293

**Pull request merged**
