### PR TITLE
Expand organization property for dashboards

### PR DESCRIPTION
**Pull request by brandonrdn**
For request #48 "add `organization` param to grafana_dashboard resource".

Also fixes syntax error where 'org_name' was used instead of 'organization' in the README

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @brandonrdn, thanks for the PR! Can you add a test for it? Did you test it locally?

**Comment by brandonrdn** [comment]
@bastelfreak I copied what was working for datasources over to dashboards, it was just a step to switch the organization before saving the dashboard. The issue we're having now is that it won't switch organizations at all (since the grafana_api_path update). I believe the way everything is written currently is broken. I've fixed part of it but am still getting some errors when creating datasources and dashboards, mostly already exists errors. So I'm making some adjustments and testing, then I'll probably push up a universal fix for all providers. Sorry for the late response, was out all last week.

**Comment by brandonrdn** [comment]
@bastelfreak The recent push should fix the bug for organizations. I did some cleanup and changed some code around, but I verified through local testing that I was able to do the following:
- Create 2 new organizations
- Create 2 datasources on each organization (3 total orgs including default)
- Create 2 dashborads on each organization

**Comment by bastelfreak** [comment]
Thanks for the patch!

**Pull request merged**
