### PR TITLE
Update repo urls

### LINKED ISSUE #278: Failure to install Grafana using module on fresh install of Debian 11
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.14.0
- Ruby: 
- Distribution: Debian bullseye
- Module version: 10.0.1

## How to reproduce (e.g Puppet code you use)

I use the following config (hiera).

```yaml
grafana::install_method: "package"
grafana::config::app_mode: "production"
```

## What are you seeing

```
Error: Execution of '/usr/bin/curl https://dl.grafana.com/oss/release/grafana_installed_amd64.deb -o /tmp/grafana.deb_20220311-1721-3ru5te -fsSLg --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404
Error: /Stage[main]/Grafana::Install/Archive[/tmp/grafana.deb]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/curl https://dl.grafana.com/oss/release/grafana_installed_amd64.deb -o /tmp/grafana.deb_20220311-1721-3ru5te -fsSLg --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404
```

## What behavior did you expect instead

I expect the module to install and configure Grafana correctly.

## Output log

N/A, provided above.

## Any additional information you'd like to impart

N/A

### PR DESCRIPTION
**Pull request by promasu**
#### Pull Request (PR) description
Grafana Labs updated their repository structure and replaced their generic packages.grafana.com with distribution specific URLs.
This PR sets the new repository URLs

#### This Pull Request (PR) fixes the following issues
Fixes #278

Refs #151

### CODE REVIEW

**Comment by promasu** [comment]
The failure of the CI checks seem to be unrelated to my changes

**Comment by bastelfreak** [comment]
@promasu can you please rebase against our master branch? that should fix the errors.

**Comment by promasu** [comment]
Perfect thanks

**Comment by promasu** [comment]
The failing CI run seems to be related to some problem on Grafana side.
I just tested on a Debian host manually:

```shell
~ # apt-cache policy grafana
grafana:
  Installed: 9.4.3
  Candidate: 9.4.3
  Version table:
 *** 9.4.3 100
        100 /var/lib/dpkg/status
     9.4.0~beta1 500
        500 https://apt.grafana.com beta/main amd64 Packages
     9.3.0~beta1 500
        500 https://apt.grafana.com beta/main amd64 Packages
     7.4.3 500
        500 https://apt.postgresql.org/pub/repos/apt bullseye-pgdg/main amd64 Packages

~ # apt install grafana=9.4.0~beta1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  grafana
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 1 not upgraded.
Need to get 84.0 MB of archives.
After this operation, 201 kB disk space will be freed.
Do you want to continue? [Y/n] y
Err:1 https://apt.grafana.com beta/main amd64 grafana amd64 9.4.0~beta1
  404  Not Found [IP: 2a04:4e42:8d::729 443]
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana/grafana_9.4.0%7ebeta1_amd64.deb  404  Not Found [IP: 2a04:4e42:8d::729 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by lbrachet** [comment]
Hi @promasu 

If I try to get the latest stable version: https://apt.grafana.com/pool/main/g/grafana/grafana_9.4.7_amd64.deb it's working from my side.

Maybe you could merge your PR + this https://github.com/voxpupuli/puppet-grafana/pull/315 in order to have the tests in good health?

**Comment by promasu** [comment]
The problem is not with the latest version but with a broken beta repository on Grafanas side

**Review by smortex — APPROVED** [review]
This looks good!

CI failures are unrelated.

**Pull request merged**
