### PR TITLE
Parametrize provisioning file names

### PR DESCRIPTION
**Pull request by kazeborja**
#### Pull Request (PR) description
This PR adds the capacity to specify the target file for provisioning files. Allowing it to adapt easily to different Grafana deployments and providing a way to create placeholder files.

### CODE REVIEW

**Comment by kazeborja** [comment]
I've spent some time looking at the failed CI, and I'm not sure it's caused by my changes, would it be possible for someone to correlate it?

Thanks in advance.

**Comment by bastelfreak** [comment]
Hi @kazeborja. Please rebase against our latest master branch. We fixed some issues in the Gemfile, afterwards travis should work again.

**Comment by kazeborja** [comment]
Rebase done. It's passing the tests but seems to crash randomly in some checks (in two different runs I've seen 272 and 273 erroring).

**Comment by bastelfreak** [comment]
One travis job died because of issues within the travis environment, I restarted the job.

**Comment by bastelfreak** [comment]
thanks @kazeborja !

**Pull request merged**
